# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    rebase-strategy: disabled
    commit-message:
      prefix: "[github-actions] "
      include: "scope"
  - package-ecosystem: docker
    directory: "/services/home"
    schedule:
      interval: "monthly"
    rebase-strategy: disabled
    commit-message:
      prefix: "[home] "
      include: "scope"
    open-pull-requests-limit: 3
  - package-ecosystem: docker
    directory: "/services/dsp"
    schedule:
      interval: "monthly"
    rebase-strategy: disabled
    commit-message:
      prefix: "[dsp] "
      include: "scope"
    open-pull-requests-limit: 3
  - package-ecosystem: docker
    directory: "/services/ssp"
    schedule:
      interval: "monthly"
    rebase-strategy: disabled
    commit-message:
      prefix: "[ssp] "
      include: "scope"
    open-pull-requests-limit: 3
  - package-ecosystem: docker
    directory: "/services/news"
    schedule:
      interval: "monthly"
    rebase-strategy: disabled
    commit-message:
      prefix: "[news] "
      include: "scope"
    open-pull-requests-limit: 3
  - package-ecosystem: docker
    directory: "/services/shop"
    schedule:
      interval: "monthly"
    rebase-strategy: disabled
    commit-message:
      prefix: "[shop] "
      include: "scope"
    open-pull-requests-limit: 3
  - package-ecosystem: docker
    directory: "/services/travel"
    schedule:
      interval: "monthly"
    rebase-strategy: disabled
    commit-message:
      prefix: "[travel] "
      include: "scope"
    open-pull-requests-limit: 3
  - package-ecosystem: docker
    directory: "/services/collector"
    schedule:
      interval: "monthly"
    rebase-strategy: disabled
    commit-message:
      prefix: "[collector] "
      include: "scope"
    open-pull-requests-limit: 3
  - package-ecosystem: npm
    directory: "/services/home"
    schedule:
      interval: "monthly"
    rebase-strategy: disabled
    commit-message:
      prefix: "[home] "
      include: "scope"
    open-pull-requests-limit: 3
